# Generated by Django 5.1.6 on 2025-02-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('contenido_thc', models.CharField(max_length=5)),
                ('contenido_cbd', models.CharField(max_length=5)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
