# Generated by Django 5.1.6 on 2025-02-21 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planta',
        ),
    ]
