# Generated by Django 5.1.6 on 2025-02-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='autofloreciente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planta',
            name='fotoperiodica',
            field=models.BooleanField(default=False),
        ),
    ]
