# Generated by Django 5.1.6 on 2025-02-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_planta_autofloreciente_planta_fotoperiodica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='plantas/'),
        ),
    ]
